//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExplorateurFichier {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Form11 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Form11()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExplorateurFichier.Form1", typeof(Form1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Microsoft Sans Serif, Size=12, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font analyser_Font {
            get {
                object obj = ResourceManager.GetObject("analyser.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=11,Y=64}.
        /// </summary>
        internal static System.Drawing.Point analyser_Location {
            get {
                object obj = ResourceManager.GetObject("analyser.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=194, Height=38}.
        /// </summary>
        internal static System.Drawing.Size analyser_Size {
            get {
                object obj = ResourceManager.GetObject("analyser.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 2.
        /// </summary>
        internal static int analyser_TabIndex {
            get {
                object obj = ResourceManager.GetObject("analyser.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyser.
        /// </summary>
        internal static string analyser_Text {
            get {
                return ResourceManager.GetString("analyser.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Arial Narrow, Size=14,25, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font btnChemin_Font {
            get {
                object obj = ResourceManager.GetObject("btnChemin.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=433,Y=30}.
        /// </summary>
        internal static System.Drawing.Point btnChemin_Location {
            get {
                object obj = ResourceManager.GetObject("btnChemin.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=36, Height=29}.
        /// </summary>
        internal static System.Drawing.Size btnChemin_Size {
            get {
                object obj = ResourceManager.GetObject("btnChemin.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        internal static int btnChemin_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btnChemin.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        internal static string btnChemin_Text {
            get {
                return ResourceManager.GetString("btnChemin.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool cbxListeFichier_AutoSize {
            get {
                object obj = ResourceManager.GetObject("cbxListeFichier.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=6,Y=88}.
        /// </summary>
        internal static System.Drawing.Point cbxListeFichier_Location {
            get {
                object obj = ResourceManager.GetObject("cbxListeFichier.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=138, Height=17}.
        /// </summary>
        internal static System.Drawing.Size cbxListeFichier_Size {
            get {
                object obj = ResourceManager.GetObject("cbxListeFichier.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 3.
        /// </summary>
        internal static int cbxListeFichier_TabIndex {
            get {
                object obj = ResourceManager.GetObject("cbxListeFichier.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des fichiers projets.
        /// </summary>
        internal static string cbxListeFichier_Text {
            get {
                return ResourceManager.GetString("cbxListeFichier.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool cbxNbFichier_AutoSize {
            get {
                object obj = ResourceManager.GetObject("cbxNbFichier.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=6,Y=19}.
        /// </summary>
        internal static System.Drawing.Point cbxNbFichier_Location {
            get {
                object obj = ResourceManager.GetObject("cbxNbFichier.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=137, Height=17}.
        /// </summary>
        internal static System.Drawing.Size cbxNbFichier_Size {
            get {
                object obj = ResourceManager.GetObject("cbxNbFichier.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        internal static int cbxNbFichier_TabIndex {
            get {
                object obj = ResourceManager.GetObject("cbxNbFichier.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre total de fichiers.
        /// </summary>
        internal static string cbxNbFichier_Text {
            get {
                return ResourceManager.GetString("cbxNbFichier.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool cbxNbFichierCs_AutoSize {
            get {
                object obj = ResourceManager.GetObject("cbxNbFichierCs.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=6,Y=42}.
        /// </summary>
        internal static System.Drawing.Point cbxNbFichierCs_Location {
            get {
                object obj = ResourceManager.GetObject("cbxNbFichierCs.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=128, Height=17}.
        /// </summary>
        internal static System.Drawing.Size cbxNbFichierCs_Size {
            get {
                object obj = ResourceManager.GetObject("cbxNbFichierCs.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 1.
        /// </summary>
        internal static int cbxNbFichierCs_TabIndex {
            get {
                object obj = ResourceManager.GetObject("cbxNbFichierCs.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de fichiers cs.
        /// </summary>
        internal static string cbxNbFichierCs_Text {
            get {
                return ResourceManager.GetString("cbxNbFichierCs.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool cbxNomFichierLong_AutoSize {
            get {
                object obj = ResourceManager.GetObject("cbxNomFichierLong.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=6,Y=65}.
        /// </summary>
        internal static System.Drawing.Point cbxNomFichierLong_Location {
            get {
                object obj = ResourceManager.GetObject("cbxNomFichierLong.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=150, Height=17}.
        /// </summary>
        internal static System.Drawing.Size cbxNomFichierLong_Size {
            get {
                object obj = ResourceManager.GetObject("cbxNomFichierLong.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 2.
        /// </summary>
        internal static int cbxNomFichierLong_TabIndex {
            get {
                object obj = ResourceManager.GetObject("cbxNomFichierLong.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom du fichier le plus long.
        /// </summary>
        internal static string cbxNomFichierLong_Text {
            get {
                return ResourceManager.GetString("cbxNomFichierLong.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ce chemin n&apos;existe pas. .
        /// </summary>
        internal static string chemin {
            get {
                return ResourceManager.GetString("chemin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=11,Y=108}.
        /// </summary>
        internal static System.Drawing.Point groupBox1_Location {
            get {
                object obj = ResourceManager.GetObject("groupBox1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=194, Height=113}.
        /// </summary>
        internal static System.Drawing.Size groupBox1_Size {
            get {
                object obj = ResourceManager.GetObject("groupBox1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 3.
        /// </summary>
        internal static int groupBox1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("groupBox1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher.
        /// </summary>
        internal static string groupBox1_Text {
            get {
                return ResourceManager.GetString("groupBox1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool label6_AutoSize {
            get {
                object obj = ResourceManager.GetObject("label6.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Microsoft Sans Serif, Size=11,25, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font label6_Font {
            get {
                object obj = ResourceManager.GetObject("label6.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=11,Y=8}.
        /// </summary>
        internal static System.Drawing.Point label6_Location {
            get {
                object obj = ResourceManager.GetObject("label6.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=109, Height=18}.
        /// </summary>
        internal static System.Drawing.Size label6_Size {
            get {
                object obj = ResourceManager.GetObject("label6.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        internal static int label6_TabIndex {
            get {
                object obj = ResourceManager.GetObject("label6.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fichiers projets.
        /// </summary>
        internal static string label6_Text {
            get {
                return ResourceManager.GetString("label6.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool lblFichier_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lblFichier.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Microsoft Sans Serif, Size=12, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font lblFichier_Font {
            get {
                object obj = ResourceManager.GetObject("lblFichier.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=13,Y=233}.
        /// </summary>
        internal static System.Drawing.Point lblFichier_Location {
            get {
                object obj = ResourceManager.GetObject("lblFichier.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=72, Height=20}.
        /// </summary>
        internal static System.Drawing.Size lblFichier_Size {
            get {
                object obj = ResourceManager.GetObject("lblFichier.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 1.
        /// </summary>
        internal static int lblFichier_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lblFichier.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 fichiers.
        /// </summary>
        internal static string lblFichier_Text {
            get {
                return ResourceManager.GetString("lblFichier.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool lblFichierCs_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lblFichierCs.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Microsoft Sans Serif, Size=12, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font lblFichierCs_Font {
            get {
                object obj = ResourceManager.GetObject("lblFichierCs.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=12,Y=264}.
        /// </summary>
        internal static System.Drawing.Point lblFichierCs_Location {
            get {
                object obj = ResourceManager.GetObject("lblFichierCs.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=92, Height=20}.
        /// </summary>
        internal static System.Drawing.Size lblFichierCs_Size {
            get {
                object obj = ResourceManager.GetObject("lblFichierCs.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 2.
        /// </summary>
        internal static int lblFichierCs_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lblFichierCs.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 fichiers cs.
        /// </summary>
        internal static string lblFichierCs_Text {
            get {
                return ResourceManager.GetString("lblFichierCs.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool lblFichierNom_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lblFichierNom.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Microsoft Sans Serif, Size=12, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font lblFichierNom_Font {
            get {
                object obj = ResourceManager.GetObject("lblFichierNom.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=13,Y=295}.
        /// </summary>
        internal static System.Drawing.Point lblFichierNom_Location {
            get {
                object obj = ResourceManager.GetObject("lblFichierNom.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=125, Height=20}.
        /// </summary>
        internal static System.Drawing.Size lblFichierNom_Size {
            get {
                object obj = ResourceManager.GetObject("lblFichierNom.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 3.
        /// </summary>
        internal static int lblFichierNom_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lblFichierNom.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom le plus long.
        /// </summary>
        internal static string lblFichierNom_Text {
            get {
                return ResourceManager.GetString("lblFichierNom.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool lblFichierNomLong_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lblFichierNomLong.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=14,Y=327}.
        /// </summary>
        internal static System.Drawing.Point lblFichierNomLong_Location {
            get {
                object obj = ResourceManager.GetObject("lblFichierNomLong.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=200, Height=0}.
        /// </summary>
        internal static System.Drawing.Size lblFichierNomLong_MaximumSize {
            get {
                object obj = ResourceManager.GetObject("lblFichierNomLong.MaximumSize", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=191, Height=26}.
        /// </summary>
        internal static System.Drawing.Size lblFichierNomLong_Size {
            get {
                object obj = ResourceManager.GetObject("lblFichierNomLong.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 4.
        /// </summary>
        internal static int lblFichierNomLong_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lblFichierNomLong.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un nom de fichier très long qui ne tient pas sur une suele ligne.
        /// </summary>
        internal static string lblFichierNomLong_Text {
            get {
                return ResourceManager.GetString("lblFichierNomLong.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool lbltitre_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lbltitre.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=8,Y=10}.
        /// </summary>
        internal static System.Drawing.Point lbltitre_Location {
            get {
                object obj = ResourceManager.GetObject("lbltitre.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=93, Height=13}.
        /// </summary>
        internal static System.Drawing.Size lbltitre_Size {
            get {
                object obj = ResourceManager.GetObject("lbltitre.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        internal static int lbltitre_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lbltitre.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dossier à analyser.
        /// </summary>
        internal static string lbltitre_Text {
            get {
                return ResourceManager.GetString("lbltitre.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fichier 1.
        /// </summary>
        internal static string listBox1_Items {
            get {
                return ResourceManager.GetString("listBox1.Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fichier 2.
        /// </summary>
        internal static string listBox1_Items1 {
            get {
                return ResourceManager.GetString("listBox1.Items1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fichier 3.
        /// </summary>
        internal static string listBox1_Items2 {
            get {
                return ResourceManager.GetString("listBox1.Items2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=224,Y=115}.
        /// </summary>
        internal static System.Drawing.Point listBox1_Location {
            get {
                object obj = ResourceManager.GetObject("listBox1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=245, Height=238}.
        /// </summary>
        internal static System.Drawing.Size listBox1_Size {
            get {
                object obj = ResourceManager.GetObject("listBox1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 4.
        /// </summary>
        internal static int listBox1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("listBox1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=224,Y=65}.
        /// </summary>
        internal static System.Drawing.Point panel1_Location {
            get {
                object obj = ResourceManager.GetObject("panel1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=245, Height=37}.
        /// </summary>
        internal static System.Drawing.Size panel1_Size {
            get {
                object obj = ResourceManager.GetObject("panel1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 11.
        /// </summary>
        internal static int panel1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("panel1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=11,Y=34}.
        /// </summary>
        internal static System.Drawing.Point textBox1_Location {
            get {
                object obj = ResourceManager.GetObject("textBox1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=416, Height=20}.
        /// </summary>
        internal static System.Drawing.Size textBox1_Size {
            get {
                object obj = ResourceManager.GetObject("textBox1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 1.
        /// </summary>
        internal static int textBox1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("textBox1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
    }
}
